version: '3'
services:
  # Database #
  db:
    image: mysql:8.0.33-debian
    restart: always
    cap_add:
      - SYS_NICE
    networks:
      - internal_network
    environment:
      - MYSQL_DATABASE=porcalabs
      - MYSQL_ROOT_PASSWORD=RootAA!23
    volumes:
      - db:/var/lib/mysql
      - ./wp-data:/docker-entrypoint-initdb.d
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
  # Phpmyadmin #
  phpmyadmin:
    links:
      - db:db
    image: phpmyadmin:5.2.1-fpm-alpine
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: RootAA!23
      UPLOAD_LIMIT: 50M
    networks:
      - internal_network
  # API #
  api:
    build: ./api
    image: api
    restart: always
    networks:
      - internal_network
    volumes:
      - api:/main
  # WordPress #
  wordpress:
    image: wordpress:6.2.2-php8.1-apache
    restart: always
    ports:
        - '9001:80'
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: porcalabs
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: RootAA!23
    depends_on:
      - db
    links:
      - db
    networks:
      - internal_network
  # WP-CLI #
  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: porcalabs
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: RootAA!23
    depends_on:
      - db
      - wordpress
    networks:
      - internal_network
  # web:
  #   build: ./web
  #   image: web
  #   restart: always
  #   networks:
  #     - internal_network
  #   depends_on:
  #     - db
  #   volumes:
  #     - web:/var/www/
  # Dozzle #
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal_network
    environment:
      DOZZLE_NO_ANALYTICS: "true"
      DOZZLE_BASE: /logs
      DOZZLE_ADDR: "0.0.0.0:1212"
  # Nginx #
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      # - web:/var/www/
      - ./wp-app:/var/www/html
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    command: ["nginx", "-g", "daemon off;"]
  # Certbot #
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  internal_network:
  external_network:

volumes:
  api:
  web:
  db:
    driver: local
